module.exports = {
    HARVESTER_NUM:5,
    UPGRASER_NUM:3,
    BUILDER_NUM:8,
    WORKER_TEMPLATE:[WORK,WORK,CARRY,CARRY,CARRY,CARRY,MOVE,MOVE,MOVE],
    SPAWN_NAME:"Spawn1",
    LOGGER_LEVEL:"DEBUG"
}