module.exports = {
    HARVESTER_NUM:6,
    UPGRASER_NUM:3,
    BUILDER_NUM:6,
    // WORKER_TEMPLATE:[WORK,WORK,WORK,WORK,WORK,CARRY,CARRY,CARRY,CARRY,CARRY,MOVE,MOVE,MOVE,MOVE,MOVE],
    WORKER_TEMPLATE:[WORK,CARRY,MOVE],
    SPAWN_NAME:"Spawn1",
    LOGGER_LEVEL:"DEBUG"
}