module.exports = {
    HARVESTER_NUM:5,
    UPGRASER_NUM:1,
    BUILDER_NUM:6,
    WORKER_TEMPLATE:[WORK,CARRY,WORK,CARRY,WORK,CARRY,WORK,CARRY,CARRY,CARRY,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE],
    SPAWN_NAME:"Spawn1",
    LOGGER_LEVEL:"INFO"
}