module.exports = {
    HARVESTER_NUM:4,
    UPGRASER_NUM:1,
    BUILDER_NUM:2,
    WORKER_TEMPLATE:[WORK,WORK,WORK,WORK,WORK,CARRY,CARRY,CARRY,CARRY,CARRY,MOVE,MOVE,MOVE,MOVE,MOVE],
    SPAWN_NAME:"Spawn1",
    LOGGER_LEVEL:"INFO"
}